In [1]:
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import numpy as np
import os
import cv2

In [3]:
IMG_WIDTH, IMG_HEIGHT = 240, 240
BATCH_SIZE = 32
EPOCHS = 25

In [5]:
data_path = "Data"

In [7]:
def load_image(path):
    img = cv2.imread(path)
    img = cv2.resize(img, (IMG_WIDTH, IMG_HEIGHT))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    img = img / 255.0
    return img

images = []
labels = []


label_map = {'Abnormal_Heartbeat': 0, 'MI_history': 1, 'Myocardial_Infarction': 2, 'Normal':3}


for folder in os.listdir(data_path):
    folder_path = os.path.join(data_path, folder)
    for file in os.listdir(folder_path):
        file_path = os.path.join(folder_path, file)
        img = load_image(file_path)
        images.append(img)
        labels.append(label_map[folder])
        print(labels)

images = np.array(images)
labels = np.array(labels)

[0]
[0, 0]
[0, 0, 0]
[0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [8]:
from keras.utils import to_categorical

labels = to_categorical(labels)

In [11]:
print(labels)

[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]


In [27]:
model = keras.Sequential([
    keras.layers.Conv2D(32, (3, 3), activation='relu', input_shape=(IMG_WIDTH, IMG_HEIGHT, 3)),
    keras.layers.MaxPooling2D((2, 2)),
    keras.layers.Conv2D(64, (3, 3), activation='relu'),
    keras.layers.MaxPooling2D((2, 2)),
    keras.layers.Flatten(),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dropout(0.2),
    keras.layers.Dense(4, activation='softmax')
])

In [50]:
model.compile(optimizer='adam',
              loss= tf.keras.losses.CategoricalCrossentropy(),
              metrics=['accuracy'])

In [31]:
print(model.summary())

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ conv2d_3 (Conv2D)                    │ (None, 238, 238, 32)        │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_3 (MaxPooling2D)       │ (None, 119, 119, 32)        │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ conv2d_4 (Conv2D)                    │ (None, 117, 117, 64)        │          18,496 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ max_pooling2d_4 (MaxPooling2D)       │ (None, 58, 58, 64)          │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ flatten_1 (Flatten)                  │ (None, 215296)              │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 128)                 │      27,558,016 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 128)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 4)                   │             516 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 27,577,924 (105.20 MB)

 Trainable params: 27,577,924 (105.20 MB)

 Non-trainable params: 0 (0.00 B)

None


In [33]:
train_images, test_images, train_labels, test_labels = train_test_split(images, labels, test_size=0.2, random_state=19)

In [34]:
print(labels.shape)
print(images.shape)

(928, 4)
(928, 240, 240, 3)


In [35]:
history = model.fit(
    train_images, train_labels,
    validation_data=(test_images, test_labels),
    epochs = EPOCHS
)

Epoch 1/25
24/24 ━━━━━━━━━━━━━━━━━━━━ 20s 694ms/step - accuracy: 0.2876 - loss: 9.7906 - val_accuracy: 0.1935 - val_loss: 1.3618
Epoch 2/25
24/24 ━━━━━━━━━━━━━━━━━━━━ 15s 626ms/step - accuracy: 0.3496 - loss: 1.3359 - val_accuracy: 0.4301 - val_loss: 1.3026
Epoch 3/25
24/24 ━━━━━━━━━━━━━━━━━━━━ 15s 622ms/step - accuracy: 0.5179 - loss: 1.1602 - val_accuracy: 0.6183 - val_loss: 0.9504
Epoch 4/25
24/24 ━━━━━━━━━━━━━━━━━━━━ 15s 624ms/step - accuracy: 0.7720 - loss: 0.7007 - val_accuracy: 0.7581 - val_loss: 0.6596
Epoch 5/25
24/24 ━━━━━━━━━━━━━━━━━━━━ 15s 606ms/step - accuracy: 0.8633 - loss: 0.4448 - val_accuracy: 0.8763 - val_loss: 0.4722
Epoch 6/25
24/24 ━━━━━━━━━━━━━━━━━━━━ 15s 618ms/step - accuracy: 0.9352 - loss: 0.2800 - val_accuracy: 0.8763 - val_loss: 0.3189
Epoch 7/25
24/24 ━━━━━━━━━━━━━━━━━━━━ 15s 611ms/step - accuracy: 0.9630 - loss: 0.1607 - val_accuracy: 0.9355 - val_loss: 0.2142
Epoch 8/25
24/24 ━━━━━━━━━━━━━━━━━━━━ 15s 617ms/step - accuracy: 0.9756 - loss: 0.1114 - val_accu

In [39]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f'Test accuracy: {test_acc:.2f}')

6/6 ━━━━━━━━━━━━━━━━━━━━ 1s 102ms/step - accuracy: 0.9570 - loss: 0.1874
Test accuracy: 0.95


In [ ]:
model.save('model.h5')

In [ ]:
import zipfile

with zipfile.ZipFile('model.h5.zip', 'w') as zip_file:
    zip_file.write('model.h5')